set -g default-command "${SHELL}"
set -as terminal-features ",alacritty*:RGB:hyperlinks"
set -g history-limit 10000
set -g renumber-windows on
set -g status-keys vi
set -g detach-on-destroy no-detached
set -g status-position top
set -g status-justify absolute-centre
set -g status-right ""
set -g status-left ""
set -g status-style "bg=terminal fg=cyan"

bind b new-session
bind c new-window -a
bind ! break-pane -a
bind @ join-pane -t ':-'
# Open terminal instance running bash without tmux
bind Enter run-shell "systemd-run --user -q bash -c 'exec \"\$\$TERMINAL\" -e /bin/bash --rcfile <(printf \"TMUX=1 ; source \~/.bashrc ; unset TMUX\")'"

bind -T copy-mode-vi [ send-keys -X previous-prompt
bind -T copy-mode-vi ] send-keys -X next-prompt
bind -T copy-mode-vi d send-keys -X halfpage-down
bind -T copy-mode-vi u send-keys -X halfpage-up
bind -T copy-mode-vi Enter send-keys -X copy-pipe

bind -n M-[ copy-mode
bind -n M-n next-window
bind -n M-p previous-window
bind -n M-, if -F '#{window_start_flag}' "move-window -at ':\$'" "swap-window -dt ':-'"
bind -n M-. if -F '#{window_end_flag}' "move-window -bt ':^'" "swap-window -dt ':+'"
# Select session and move current window into it
bind -n M-s choose-tree -s "move-window -at '%1' ; set-hook -R window-unlinked ; switch-client -t '%1'"
# Move current window into a new session
bind -n M-Enter new-session \; run-shell -C "move-window -s '=#{client_last_session}:' -t ':#{window_id}' -k ; move-window -rt '=#{client_last_session}:' ; set-hook -Rt '=#{client_last_session}:' window-unlinked"
bind -n M-c new-window -ac '#{pane_current_path}'
bind -n "M-%" split-window -hc '#{pane_current_path}'
bind -n 'M-"' split-window -c '#{pane_current_path}'
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-Up resize-pane -U
bind -n M-Down resize-pane -D
bind -n M-Left resize-pane -L
bind -n M-Right resize-pane -R

set -g status off
set-hook -g window-linked "if -F '#{==:#{session_windows},2}' 'set status on'"
set-hook -g window-unlinked "if -F '#{==:#{session_windows},1}' 'set status off'"
