[general]
import = [
  "~/.config/alacritty/cyberdream.toml",
]

[window]
decorations = "none"
startup_mode = "Fullscreen"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]

[mouse]
hide_when_typing = true
