[general]
import = [
  "~/.config/alacritty/cyberdream.toml",
]

[window]
decorations = "none"
startup_mode = "Fullscreen"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },  # https://wiki.archlinux.org/title/Alacritty#Spawn_new_instance_in_same_directory
]
